spring.application.name=lab05

# ========================
# MySQL Data Source Config
# ========================
spring.datasource.url=jdbc:mysql://localhost:3306/j2ee?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================
# JPA / Hibernate Config
# ========================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================
# Thymeleaf Config
# ========================
spring.thymeleaf.cache=false
